# Generated by Django 5.2.16 on 2026-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_title_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
