# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phase2_email_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
