# Generated by Django 5.2.16 on 2026-08-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_phase2_models_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='type',
            field=models.CharField(choices=[('lead_import', 'Lead Import'), ('forecast_export', 'Forecast Export'), ('analytics_export', 'Analytics Export'), ('demo_reset', 'Demo Reset'), ('stale_scan', 'Stale Deal Scan'), ('cache_warm', 'Cache Warm'), ('sequence_advance', 'Sequence Advance')], max_length=40),
        ),
    ]
