# Generated by Django 5.2.16 on 2026-08-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_dealcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('account', 'Account'), ('contact', 'Contact'), ('opportunity', 'Opportunity')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('stage_change', 'Stage change'), ('status_change', 'Status change'), ('created', 'Created'), ('merged', 'Merged'), ('note', 'Note'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='crm_timelin_entity__07eb09_idx'), models.Index(fields=['account', '-occurred_at'], name='crm_timelin_account_b7d53c_idx'), models.Index(fields=['contact', '-occurred_at'], name='crm_timelin_contact_a39e5d_idx'), models.Index(fields=['lead', '-occurred_at'], name='crm_timelin_lead_id_3f28d5_idx'), models.Index(fields=['opportunity', '-occurred_at'], name='crm_timelin_opportu_7bd39a_idx')],
            },
        ),
    ]
