# Generated by Django 5.2.16 on 2026-08-02 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_phase3_quotes_scoring_health'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('lead', 'Lead'), ('account', 'Account'), ('contact', 'Contact'), ('opportunity', 'Opportunity')], max_length=20)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('select', 'Select'), ('date', 'Date')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Select options as a list of strings')),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['entity', 'label'],
                'unique_together': {('entity', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, help_text='Optional industry match hint for routing/assignment', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='territories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'territories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='crm.territory'),
        ),
        migrations.AddField(
            model_name='leadroutingrule',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='When set, round-robin only among SDRs in this territory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='crm.territory'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('stage', 'Stage change'), ('owner', 'Owner change'), ('status', 'Status change')], max_length=20)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('account', 'Account'), ('contact', 'Contact'), ('opportunity', 'Opportunity')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='crm_auditev_entity__f96d24_idx'), models.Index(fields=['actor', '-occurred_at'], name='crm_auditev_actor_i_a4faf1_idx'), models.Index(fields=['action', '-occurred_at'], name='crm_auditev_action_df3333_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('account', 'Account'), ('contact', 'Contact'), ('opportunity', 'Opportunity')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crm.customfielddefinition')),
            ],
            options={
                'ordering': ['definition__label'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='crm_customf_entity__759920_idx'), models.Index(fields=['definition', 'value_text'], name='crm_customf_definit_dabac4_idx')],
                'unique_together': {('definition', 'entity_type', 'entity_id')},
            },
        ),
    ]
