# Generated by Django 5.2.16 on 2026-08-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_phase4_custom_fields_territories_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('summary', 'Deal summary'), ('next_action', 'Next-best action'), ('email_draft', 'Email draft'), ('score_overlay', 'Lead score overlay')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('output_text', models.TextField(blank=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='rules', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', 'kind', '-created_at'], name='crm_aisugge_opportu_0df2e0_idx'), models.Index(fields=['lead', 'kind', '-created_at'], name='crm_aisugge_lead_id_1a4f89_idx')],
            },
        ),
    ]
