# Generated by Django 5.2.16 on 2026-08-02 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


BUDGET_MAP = {
    "<$10k": 1000,
    "$10k–50k": 10000,
    "$10k-50k": 10000,
    "$50k+": 50000,
}


def forwards_data(apps, schema_editor):
    DealComment = apps.get_model("crm", "DealComment")
    Comment = apps.get_model("crm", "Comment")
    Task = apps.get_model("crm", "Task")
    Lead = apps.get_model("crm", "Lead")
    CustomFieldDefinition = apps.get_model("crm", "CustomFieldDefinition")
    CustomFieldValue = apps.get_model("crm", "CustomFieldValue")

    for dc in DealComment.objects.all().iterator():
        Comment.objects.create(
            author_id=dc.author_id,
            body=dc.body,
            opportunity_id=dc.opportunity_id,
            created_at=dc.created_at,
            updated_at=dc.updated_at,
        )

    Task.objects.filter(completed=True).update(status="done")
    Task.objects.filter(completed=False).update(status="todo")

    budget_def = CustomFieldDefinition.objects.filter(entity="lead", key="budget_range").first()
    if budget_def:
        for row in CustomFieldValue.objects.filter(definition=budget_def, entity_type="lead"):
            amount = BUDGET_MAP.get((row.value_text or "").strip())
            if amount is not None:
                Lead.objects.filter(pk=row.entity_id).update(budget_amount=amount)
        budget_def.is_active = False
        budget_def.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_phase5_ai_realtime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="budget_amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Budget in USD dollars; UI slider starts at 1000.", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="job_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_meetings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="target_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SDR", "Sales Development"),
                    ("AE", "Account Executive"),
                    ("MANAGER", "Sales Manager"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sequenceenrollment",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sequenceenrollment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequencestep",
            name="step_type",
            field=models.CharField(choices=[("email", "Email")], default="email", max_length=20),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="crm.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To do"),
                    ("in_progress", "In progress"),
                    ("blocked", "Blocked"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dealcomment",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_comments",
                to="crm.opportunity",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="crm.lead",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="crm.meeting",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="crm.opportunity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="crm.comment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="crm.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(forwards_data, migrations.RunPython.noop),
    ]
